deployment:
  name: whoami-deployment
  app: whoami
  container:
    name: whoami
    image: traefik/whoami
    args:
      - "-cert"
      - "/etc/tls/tls.crt"
      - "-key"
      - "/etc/tls/tls.key"
      - "-port"
      - "443"
    port: 443
  volume:
    name: tls
    mountPath: /etc/tls
    secretName: my-tls-secret
  nodeSelector:
    kubernetes.io/arch: amd64
    eks.amazonaws.com/nodegroup: managed-ng-1

service:
  name: whoami-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
  type: LoadBalancer
  app: whoami
  protocol: TCP