---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
        args:
        - "-cert"
        - "/etc/tls/tls.crt"
        - "-key"
        - "/etc/tls/tls.key"
        - "-port"
        - "443"
        ports:
        - containerPort: 443
        volumeMounts:
        - name: tls
          mountPath: /etc/tls
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: my-tls-secret
      nodeSelector:
        kubernetes.io/arch : amd64
        eks.amazonaws.com/nodegroup: managed-ng-1
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
spec:
  type: LoadBalancer
  selector:
    app: whoami
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  externalTrafficPolicy: Local