---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations: 
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.app }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}