apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations: {{ .Values.service.annotations }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.app }}
  ports:
    - protocol: {{ .Values.service.protocol }}